### ISSUE TITLE
How can I get the photo when motion detected ？

### ISSUE THREAD

**Issue by ylc395** [nazrhom/node-pi-motion#2]
Thanks for your nice job, but may I ask how to get the photo when motion detected?

**Comment by nazrhom** [comment]
Thanks @ylc395 unfortunately there is no support for that as pi-motion-lite only tells you that it detected motion without returning any picture. 
I guess you can try using something like https://www.npmjs.com/package/node-raspistill as soon as motion is detected for a decent approximation.

**Comment by ylc395** [comment]
thank you for your reply
